import { useRef, useState } from "react";
import { useSelector } from "react-redux";
import { Link, useSearchParams } from "react-router-dom";
import { toast } from "react-toastify";
import {
  useGetStudentsQuery,
  useCreateStudentMutation,
  useUpdateStudentMutation,
  useImportStudentsExcelMutation,
  useGetStudentCustomFieldsQuery,
  useGetFeeCustomFieldsQuery,
  useUpdateFeeCustomFieldMutation,
  useDeleteFeeCustomFieldMutation,
  useImportFeesExcelMutation,
} from "../app/api";
import Pagination from "../components/Pagination";
import usePagination from "../hooks/usePagination";

function FeeColumnRow({ field }) {
  const [name, setName] = useState(field.name);
  const [updateField, { isLoading }] = useUpdateFeeCustomFieldMutation();
  const [deleteField] = useDeleteFeeCustomFieldMutation();

  const handleSave = async () => {
    if (!name.trim() || name.trim() === field.name) return;
    try {
      await updateField({ id: field.id, name: name.trim() }).unwrap();
      toast.success(`Column renamed to "${name.trim()}"`);
    } catch (err) {
      toast.error(err?.data?.message || "Failed to rename column");
      setName(field.name);
    }
  };

  return (
    <div className="flex items-center gap-2">
      <input
        className="input"
        value={name}
        onChange={(e) => setName(e.target.value)}
      />
      <button
        className="btn-secondary"
        disabled={isLoading}
        onClick={handleSave}
      >
        Save
      </button>
      <button
        className="text-red-600 text-sm hover:underline"
        onClick={() => deleteField(field.id)}
      >
        Delete
      </button>
    </div>
  );
}

function FeeManagementPanel({ canManageColumns }) {
  const { data: customFields = [] } = useGetFeeCustomFieldsQuery();
  const [importFeesExcel, { isLoading: importing }] =
    useImportFeesExcelMutation();
  const [semesterLabel, setSemesterLabel] = useState("");
  const fileRef = useRef();

  const handleImport = async (e) => {
    const file = e.target.files[0];
    if (!file) return;
    if (!semesterLabel.trim()) {
      toast.error('Pehle Semester Label likho (e.g. "Fall 2026")');
      fileRef.current.value = "";
      return;
    }
    const formData = new FormData();
    formData.append("file", file);
    formData.append("semesterLabel", semesterLabel.trim());
    try {
      const res = await importFeesExcel(formData).unwrap();
      const roadmapNote = res.semestersAutoGeneratedCount
        ? ` Semester roadmap auto-generated for ${res.semestersAutoGeneratedCount} student(s) from Adm Session.`
        : "";
      toast.success(
        `Imported: ${res.createdCount} new fee rows, ${res.updatedCount} updated. New students created: ${res.studentsCreatedCount}. Skipped: ${res.skippedCount}. New columns: ${res.newColumnsCreated.length}.${roadmapNote}`,
      );
    } catch (err) {
      toast.error(err?.data?.message || "Fee import failed");
    } finally {
      fileRef.current.value = "";
    }
  };

  return (
    <div className="space-y-4">
      <div className="card space-y-3">
        <h2 className="font-semibold">Bulk Fee Import (Excel)</h2>
        <p className="text-xs text-gray-500">
          Excel sheet ka koi bhi column pehle se fix nahi hai — jo bhi header
          sheet mein likha hoga, wahi naam aur wahi data system mein dynamic
          column ban ke aa jayega. Naye columns khud-b-khud create ho jate hain.
          Agar sheet mein "Adm Session" (e.g. "Spring 2022") aur "Degree Years"
          (e.g. "4") columns hon, to system har student ka poora semester
          roadmap khud admission session se shuru kar ke bana deta hai (Spring
          2022, Fall 2022, Spring 2023, Fall 2023, …) — sirf pehli dafa, dobara
          import karne par duplicate nahi banata.
        </p>
        <div className="flex flex-wrap items-end gap-2">
          <div>
            <label className="text-xs text-gray-500">Semester Label</label>
            <input
              className="input mt-1 w-48"
              placeholder='e.g. "Fall 2026"'
              value={semesterLabel}
              onChange={(e) => setSemesterLabel(e.target.value)}
            />
          </div>
          <input
            ref={fileRef}
            type="file"
            accept=".xlsx,.xls,.csv"
            className="hidden"
            onChange={handleImport}
          />
          <button
            className="btn-primary"
            disabled={importing}
            onClick={() => fileRef.current.click()}
          >
            {importing ? "Importing…" : "📥 Import Fee Excel"}
          </button>
        </div>
      </div>

      {canManageColumns && (
        <div className="card space-y-3">
          <h2 className="font-semibold">Manage Fee Columns</h2>
          {customFields.length === 0 && (
            <p className="text-sm text-gray-400">
              Abhi koi custom fee column nahi hai.
            </p>
          )}
          <div className="space-y-2">
            {customFields.map((f) => (
              <FeeColumnRow key={f.id} field={f} />
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export default function Students() {
  const user = useSelector((state) => state.auth.user);
  const [searchParams] = useSearchParams();
  const isFeeMode = searchParams.get("mode") === "fee";
  const [search, setSearch] = useState("");
  const [filters, setFilters] = useState({
    category: "",
    program: "",
    missingMatric: false,
    missingInter: false,
    missingDegreeSession: false,
  });

  const studentsQueryParams = {
    ...(search.trim() ? { search: search.trim() } : {}),
    ...(filters.category ? { category: filters.category } : {}),
    ...(filters.program ? { program: filters.program } : {}),
    ...(filters.missingMatric ? { missingMatric: "true" } : {}),
    ...(filters.missingInter ? { missingInter: "true" } : {}),
    ...(filters.missingDegreeSession ? { missingDegreeSession: "true" } : {}),
    // mine=true can be enabled later if this page needs it; controller already supports it.
  };

  const { data: students = [], isLoading } =
    useGetStudentsQuery(studentsQueryParams);

  const { page, setPage, totalPages, totalItems, pageSize, paginatedItems: paginatedStudents } =
    usePagination(students, 10);

  // Every column that showed up in an imported Admission Excel and isn't one of
  // the fixed fields below (Name, CNIC, Program, etc.) — rendered as extra table
  // columns so the UI mirrors the sheet instead of hiding data.
  const { data: studentCustomFields = [] } = useGetStudentCustomFieldsQuery(
    undefined,
    { skip: isFeeMode },
  );

  const [createStudent] = useCreateStudentMutation();
  const [importStudentsExcel, { isLoading: importingStudents }] =
    useImportStudentsExcelMutation();
  const [showCreate, setShowCreate] = useState(false);
  const fileRef = useRef();

  const canManage = ["Manager", "AccountsManager", "StudentAffair"].includes(
    user?.role,
  );
  // Renaming/deleting fee columns stays restricted to Manager/AccountsManager —
  // everything else (adding students, importing admission/fee Excel, editing
  // program duration) is open to Student Affair too.
  const canManageColumns = ["Manager", "AccountsManager"].includes(user?.role);
  const [updateStudent] = useUpdateStudentMutation();

  // Admission mode: Enrollment#, Registration ID, Name, CNIC, Section, Program,
  // Email + one column per dynamic custom field from the imported Excel.
  // Fee mode: Enrollment#, Name, Section, Program, Duration, Email + action link.
  const colCount = isFeeMode ? 7 : 7 + studentCustomFields.length;

  const [form, setForm] = useState({
    enrollmentNumber: "",
    registrationId: "",
    name: "",
    cnic: "",
    section: "",
    program: "",
    email: "",
    semesterSystem: "5-year",
  });

  const handleCreate = async (e) => {
    e.preventDefault();
    try {
      await createStudent(form).unwrap();
      toast.success("Student added successfully");
      setShowCreate(false);
      setForm({
        enrollmentNumber: "",
        registrationId: "",
        name: "",
        cnic: "",
        section: "",
        program: "",
        email: "",
        semesterSystem: "5-year",
      });
    } catch (err) {
      toast.error(err?.data?.message || "Failed to add student");
    }
  };

  const handleChangeDuration = async (studentId, semesterSystem) => {
    try {
      await updateStudent({ id: studentId, semesterSystem }).unwrap();
      toast.success(`Program duration set to ${semesterSystem}`);
    } catch (err) {
      toast.error(err?.data?.message || "Failed to update program duration");
    }
  };

  const handleFileChange = async (e) => {
    const file = e.target.files[0];
    if (!file) return;
    const formData = new FormData();
    formData.append("file", file);
    try {
      const res = await importStudentsExcel(formData).unwrap();
      toast.success(
        `Naye students: ${res.createdCount}. Duplicate (skip): ${res.skippedDuplicateCount}. Nayi columns: ${res.newColumnsCreated.length}.`,
      );
    } catch (err) {
      toast.error(err?.data?.message || "Import failed");
    } finally {
      fileRef.current.value = "";
    }
  };

  return (
    <div className="space-y-5">
      {isFeeMode && canManage && (
        <FeeManagementPanel canManageColumns={canManageColumns} />
      )}

      <div className="flex flex-wrap items-center justify-between gap-3">
        <h1 className="text-xl font-bold">
          {isFeeMode ? "Fee Detail — Students" : "Students"}
        </h1>
        {canManage && (
          <div className="flex flex-wrap items-end gap-2">
            {!isFeeMode && (
              <>
                <input
                  ref={fileRef}
                  type="file"
                  accept=".xlsx,.xls,.csv"
                  className="hidden"
                  onChange={handleFileChange}
                />
                <button
                  className="btn-secondary"
                  onClick={() => fileRef.current.click()}
                  disabled={importingStudents}
                  title="Admission Excel import karo — koi bhi column ho, khud dynamically system mein ban jayega"
                >
                  {importingStudents
                    ? "Importing…"
                    : "📥 Import Admission Excel"}
                </button>
              </>
            )}
            <button className="btn-primary" onClick={() => setShowCreate(true)}>
              + Add Student
            </button>
          </div>
        )}
      </div>

      <div className="card p-3 space-y-3">
        <div className="flex flex-wrap items-center gap-3">
          <input
            className="input max-w-sm"
            placeholder="Search by Enrollment Number…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />

          <input
            className="input w-52"
            placeholder="Category (exact match)"
            value={filters.category}
            onChange={(e) =>
              setFilters((prev) => ({ ...prev, category: e.target.value }))
            }
          />

          <input
            className="input w-52"
            placeholder="Program"
            value={filters.program}
            onChange={(e) =>
              setFilters((prev) => ({ ...prev, program: e.target.value }))
            }
          />

          <button
            className="btn-secondary"
            type="button"
            onClick={() =>
              setFilters({
                category: "",
                program: "",
                missingMatric: false,
                missingInter: false,
                missingDegreeSession: false,
              })
            }
          >
            Reset
          </button>
        </div>

        <div className="flex flex-wrap items-center gap-4 text-sm">
          <label className="flex items-center gap-2">
            <input
              type="checkbox"
              checked={filters.missingMatric}
              onChange={(e) =>
                setFilters((prev) => ({
                  ...prev,
                  missingMatric: e.target.checked,
                }))
              }
            />
            Missing Matric
          </label>

          <label className="flex items-center gap-2">
            <input
              type="checkbox"
              checked={filters.missingInter}
              onChange={(e) =>
                setFilters((prev) => ({
                  ...prev,
                  missingInter: e.target.checked,
                }))
              }
            />
            Missing Intermediate
          </label>

          <label className="flex items-center gap-2">
            <input
              type="checkbox"
              checked={filters.missingDegreeSession}
              onChange={(e) =>
                setFilters((prev) => ({
                  ...prev,
                  missingDegreeSession: e.target.checked,
                }))
              }
            />
            Missing Degree
          </label>
        </div>
      </div>

      <div className="card overflow-x-auto">
        <table className="data-table">
          <thead>
            <tr>
              <th>Enrollment #</th>
              {!isFeeMode && <th>Registration/Applicant ID</th>}
              <th>Name</th>
              {!isFeeMode && <th>CNIC</th>}
              <th>Section</th>
              <th>Program</th>
              {isFeeMode && <th>Duration</th>}
              <th>Email</th>
              {!isFeeMode &&
                studentCustomFields.map((f) => <th key={f.id}>{f.name}</th>)}
              {isFeeMode && <th></th>}
            </tr>
          </thead>
          <tbody>
            {isLoading && (
              <tr>
                <td
                  colSpan={colCount}
                  className="text-center text-gray-400 py-6"
                >
                  Loading…
                </td>
              </tr>
            )}
            {!isLoading && students.length === 0 && (
              <tr>
                <td
                  colSpan={colCount}
                  className="text-center text-gray-400 py-6"
                >
                  No students found
                </td>
              </tr>
            )}
            {paginatedStudents.map((s) => (
              <tr key={s.id}>
                <td className="font-medium">{s.enrollmentNumber}</td>
                {!isFeeMode && <td>{s.registrationId || "—"}</td>}
                <td>{s.name}</td>
                {!isFeeMode && <td>{s.cnic || "—"}</td>}
                <td>{s.section || "—"}</td>
                <td>{s.program || "—"}</td>
                {isFeeMode && (
                  <td>
                    {s.programDurationYears ? (
                      <span
                        className="text-xs text-gray-600"
                        title="Fee import ke 'Adm Session' + 'Degree Years' columns se khud-b-khud set hua"
                      >
                        {s.programDurationYears}-year (
                        {s.programDurationYears * 2} semesters) — auto
                      </span>
                    ) : canManage ? (
                      <select
                        className="input py-1 text-sm"
                        value={s.semesterSystem || "5-year"}
                        onChange={(e) =>
                          handleChangeDuration(s.id, e.target.value)
                        }
                      >
                        <option value="4-year">4-year (8 semesters)</option>
                        <option value="5-year">5-year (10 semesters)</option>
                      </select>
                    ) : (
                      s.semesterSystem || "—"
                    )}
                  </td>
                )}
                <td>{s.email || "—"}</td>
                {!isFeeMode &&
                  studentCustomFields.map((f) => (
                    <td key={f.id} className="whitespace-nowrap">
                      {s.customFields?.[f.name] ?? "—"}
                    </td>
                  ))}
                {isFeeMode && (
                  <td>
                    <Link
                      to={`/students/${s.id}/fee`}
                      className="text-primary-600 text-sm hover:underline"
                    >
                      Fee Page →
                    </Link>
                  </td>
                )}
              </tr>
            ))}
          </tbody>
        </table>
        <Pagination
          currentPage={page}
          totalPages={totalPages}
          onPageChange={setPage}
          totalItems={totalItems}
          pageSize={pageSize}
        />
      </div>

      {showCreate && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50 px-4">
          <div className="bg-white dark:bg-gray-900 rounded-xl p-6 w-full max-w-md">
            <h2 className="font-semibold mb-4">Add New Student</h2>
            <form onSubmit={handleCreate} className="space-y-3">
              <input
                required
                className="input"
                placeholder="Enrollment Number"
                value={form.enrollmentNumber}
                onChange={(e) =>
                  setForm({ ...form, enrollmentNumber: e.target.value })
                }
              />
              <input
                className="input"
                placeholder="Registration/Applicant ID (optional)"
                value={form.registrationId}
                onChange={(e) =>
                  setForm({ ...form, registrationId: e.target.value })
                }
              />
              <input
                required
                className="input"
                placeholder="Full Name"
                value={form.name}
                onChange={(e) => setForm({ ...form, name: e.target.value })}
              />
              <input
                className="input"
                placeholder="CNIC (optional)"
                value={form.cnic}
                onChange={(e) => setForm({ ...form, cnic: e.target.value })}
              />
              <input
                className="input"
                placeholder="Section"
                value={form.section}
                onChange={(e) => setForm({ ...form, section: e.target.value })}
              />
              <input
                className="input"
                placeholder="Program"
                value={form.program}
                onChange={(e) => setForm({ ...form, program: e.target.value })}
              />
              <div>
                <label className="text-xs text-gray-500">
                  Program Duration
                </label>
                <select
                  className="input mt-1"
                  value={form.semesterSystem}
                  onChange={(e) =>
                    setForm({ ...form, semesterSystem: e.target.value })
                  }
                >
                  <option value="4-year">4-year (8 semesters)</option>
                  <option value="5-year">5-year (10 semesters)</option>
                </select>
              </div>
              <input
                type="email"
                className="input"
                placeholder="Email"
                value={form.email}
                onChange={(e) => setForm({ ...form, email: e.target.value })}
              />
              <div className="flex gap-2 pt-2">
                <button
                  type="button"
                  className="btn-secondary flex-1"
                  onClick={() => setShowCreate(false)}
                >
                  Cancel
                </button>
                <button type="submit" className="btn-primary flex-1">
                  Save
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
