export const SIDEBAR_CONFIG = {
  Manager: [
    { label: "Dashboard", path: "/dashboard" },
    { label: "Full Student Profile", path: "/full-profile" },
    { label: "Applications", path: "/applications" },
    { label: "Create Application", path: "/create-application" },
    { label: "Fee Detail", path: "/students?mode=fee" },
    { label: "Students", path: "/students" },
    { label: "Academic Records", path: "/academic-records" },
    { label: "Admission Center", path: "/admission-center" },
    { label: "HR", path: "/hr" },
    { label: "Generate Slip", path: "/clearance-slip" },
    { label: "Scan Slip", path: "/clearance-scanner" },
    { label: "User Management", path: "/users" },
  ],
  AccountsManager: [
    { label: "Dashboard", path: "/dashboard" },
    { label: "Applications", path: "/applications" },
    { label: "Fee Detail", path: "/students?mode=fee" },
    { label: "Students", path: "/students" },
    { label: "Generate Slip", path: "/clearance-slip" },
    { label: "Scan Slip", path: "/clearance-scanner" },
  ],
  StudentAffair: [
    { label: "Dashboard", path: "/dashboard" },
    { label: "Applications", path: "/applications" },
    { label: "Fee Detail", path: "/students?mode=fee" },
    { label: "Students", path: "/students" },
    { label: "Scan Slip", path: "/clearance-scanner" },
  ],
  DataEntry: [
    { label: "Create Application", path: "/create-application" },
    { label: "My Applications", path: "/applications" },
  ],
  RecordRoom: [
    { label: "Applications", path: "/applications" },
    { label: "Academic Records", path: "/academic-records" },
  ],
  // Registrar can view every page in the project.
  Registrar: [
    { label: "Dashboard", path: "/dashboard" },
    { label: "Full Student Profile", path: "/full-profile" },
    { label: "Applications", path: "/applications" },
    { label: "Create Application", path: "/create-application" },
    { label: "Fee Detail", path: "/students?mode=fee" },
    { label: "Students", path: "/students" },
    { label: "Academic Records", path: "/academic-records" },
    { label: "Admission Center", path: "/admission-center" },
    { label: "HR", path: "/hr" },
    { label: "Generate Slip", path: "/clearance-slip" },
    { label: "Scan Slip", path: "/clearance-scanner" },
  ],
  AdmissionCenter: [{ label: "Admission Center", path: "/admission-center" }],
  HR: [{ label: "HR", path: "/hr" }],
};

export const ROLE_LABELS = {
  Manager: "Manager",
  AccountsManager: "Accounts Manager",
  StudentAffair: "Student Affair",
  DataEntry: "Data Entry",
  RecordRoom: "Record Room",
  Registrar: "Registrar",
  AdmissionCenter: "Admission Center",
  HR: "HR",
};
